city2iata = {
    "Aberdeen": "ABZ",
    "Abu Dhabi": "AUH",
    "Agadir": "AGA",
    "Alesund": "AES",
    "Alexandria": "HBE",
    "Alghero": "AHO",
    "Alicante": "ALC",
    "Almaty": "ALA",
    "Amman": "AMM",
    "Ancona": "AOI",
    "Antalya": "AYT",
    "Aqaba": "AQJ",
    "Astana": "NQZ",
    "Athens": "ATH",
    "Bacau": "BCM",
    "Baku": "GYD",
    "Banja Luka": "BNX",
    "Barcelona": "BCN",
    "Bari": "BRI",
    "Basel (BSL)": "BSL",
    "Basel (MLH)": "MLH",
    "Belgrade": "BEG",
    "Bergen": "BGO",
    "Berlin": "BER",
    "Bilbao": "BIO",
    "Billund": "BLL",
    "Birmingham": "BHX",
    "Bishkek": "FRU",
    "Bologna": "BLQ",
    "Bourgas": "BOJ",
    "Brasov": "GHV",
    "Bratislava": "BTS",
    "Bremen": "BRE",
    "Brindisi": "BDS",
    "Brussels": "BRU",
    "Brussels Charleroi": "CRL",
    "Bucharest": "OTP",
    "Bucharest Baneasa": "BBU",
    "Budapest": "BUD",
    "Cairo": "SPX",
    "Castellon": "CDT",
    "Catania": "CTA",
    "Chania": "CHQ",
    "Chisinau": "RMO",
    "Cluj-Napoca": "CLJ",
    "Cologne": "CGN",
    "Comiso": "CIY",
    "Constanta": "CND",
    "Copenhagen": "CPH",
    "Corfu": "CFU",
    "Craiova": "CRA",
    "Dalaman": "DLM",
    "Dammam": "DMM",
    "Debrecen": "DEB",
    "Dortmund": "DTM",
    "Dubai": "DXB",
    "Dubrovnik": "DBV",
    "Eindhoven": "EIN",
    "Erbil": "EBL",
    "Faro": "FAO",
    "Frankfurt": "HHN",
    "Friedrichshafen": "FDH",
    "Fuerteventura": "FUE",
    "Funchal": "FNC",
    "Gdansk": "GDN",
    "Geneva": "GVA",
    "Genoa": "GOA",
    "Girona": "GRO",
    "Glasgow": "GLA",
    "Gothenburg": "GOT",
    "Gran Canaria": "LPA",
    "Grenoble": "GNB",
    "Hamburg": "HAM",
    "Haugesund": "HAU",
    "Heraklion": "HER",
    "Hurghada": "HRG",
    "Iasi": "IAS",
    "Ibiza": "IBZ",
    "Istanbul": "IST",
    "Izmir": "ADB",
    "Jeddah": "JED",
    "Karlsruhe/Baden-Baden": "FKB",
    "Katowice": "KTW",
    "Kaunas": "KUN",
    "Kefalonia": "EFL",
    "Kos": "KGS",
    "Kosice": "KSC",
    "Krakow": "KRK",
    "Kutaisi": "KUT",
    "Lampedusa": "LMP",
    "Larnaca": "LCA",
    "Leeds": "LBA",
    "Leipzig": "LEJ",
    "Lisbon": "LIS",
    "Liverpool": "LPL",
    "Ljubljana": "LJU",
    "London Gatwick": "LGW",
    "London Luton": "LTN",
    "Lublin": "LUZ",
    "Lyon": "LYS",
    "Madinah": "MED",
    "Madrid": "MAD",
    "Malaga": "AGP",
    "Malmo": "MMX",
    "Malta": "MLA",
    "Male": "MLE",
    "Marrakesh": "RAK",
    "Marsa Alam": "RMF",
    "Memmingen": "FMM",
    "Milan Bergamo": "BGY",
    "Milan Malpensa": "MXP",
    "Muscat": "MCT",
    "Mykonos": "JMK",
    "Naples": "NAP",
    "Nice": "NCE",
    "Nis": "INI",
    "Nuremberg": "NUE",
    "Ohrid": "OHD",
    "Olbia": "OLB",
    "Oslo Gardermoen": "OSL",
    "Oslo Sandefjord Torp": "TRF",
    "Palma de Mallorca": "PMI",
    "Paris Beauvais": "BVA",
    "Paris Orly": "ORY",
    "Perugia": "PEG",
    "Pescara": "PSR",
    "Pisa": "PSA",
    "Plovdiv": "PDV",
    "Podgorica": "TGD",
    "Poprad-Tatry": "TAT",
    "Porto": "OPO",
    "Poznan": "POZ",
    "Prague": "PRG",
    "Prishtina": "PRN",
    "Radom": "RDO",
    "Reykjavik": "KEF",
    "Rhodes": "RHO",
    "Riga": "RIX",
    "Rimini": "RMI",
    "Riyadh": "RUH",
    "Rome Ciampino": "CIA",
    "Rome Fiumicino": "FCO",
    "Rzeszow": "RZE",
    "Salalah": "SLL",
    "Salerno": "QSR",
    "Salzburg": "SZG",
    "Samarkand": "SKD",
    "Santander": "SDR",
    "Santorini": "JTR",
    "Sarajevo": "SJJ",
    "Satu Mare": "SUJ",
    "Seville": "SVQ",
    "Sharm El Sheikh": "SSH",
    "Sibiu": "SBZ",
    "Skiathos": "JSI",
    "Skopje": "SKP",
    "Sofia": "SOF",
    "Sohag": "HMB",
    "Split": "SPU",
    "Stavanger": "SVG",
    "Stockholm Arlanda": "ARN",
    "Stockholm Skavsta": "NYO",
    "Stuttgart": "STR",
    "Suceava": "SCV",
    "Szczecin": "SZZ",
    "Tallinn": "TLL",
    "Tashkent": "TAS",
    "Tel-Aviv": "TLV",
    "Tenerife": "TFS",
    "Thessaloniki": "SKG",
    "Timisoara": "TSR",
    "Tirana": "TIA",
    "Tirgu Mures": "TGM",
    "Trieste": "TRS",
    "Tromso": "TOS",
    "Trondheim": "TRD",
    "Turin": "TRN",
    "Turkistan": "HSA",
    "Turku": "TKU",
    "Tuzla": "TZL",
    "Valencia": "VLC",
    "Varna": "VAR",
    "Venice Marco Polo": "VCE",
    "Venice Treviso": "TSF",
    "Verona": "VRN",
    "Vienna": "VIE",
    "Vilnius": "VNO",
    "Warsaw Chopin": "WAW",
    "Wroclaw": "WRO",
    "Yerevan": "EVN",
    "Zakynthos": "ZTH",
    "Zaragoza": "ZAZ",
}


iata2city = {
    "ABZ": "Aberdeen",
    "AUH": "Abu Dhabi",
    "AGA": "Agadir",
    "AES": "Alesund",
    "HBE": "Alexandria",
    "AHO": "Alghero",
    "ALC": "Alicante",
    "ALA": "Almaty",
    "AMM": "Amman",
    "AOI": "Ancona",
    "AYT": "Antalya",
    "AQJ": "Aqaba",
    "NQZ": "Astana",
    "ATH": "Athens",
    "BCM": "Bacau",
    "GYD": "Baku",
    "BNX": "Banja Luka",
    "BCN": "Barcelona",
    "BRI": "Bari",
    "BSL": "Basel (BSL)",
    "MLH": "Basel (MLH)",
    "BEG": "Belgrade",
    "BGO": "Bergen",
    "BER": "Berlin",
    "BIO": "Bilbao",
    "BLL": "Billund",
    "BHX": "Birmingham",
    "FRU": "Bishkek",
    "BLQ": "Bologna",
    "BOJ": "Burgas",
    "GHV": "Brasov",
    "BTS": "Bratislava",
    "BRE": "Bremen",
    "BDS": "Brindisi",
    "BRU": "Brussels",
    "CRL": "Brussels Charleroi",
    "OTP": "Bucharest",
    "BUD": "Budapest",
    "CDT": "Castellon",
    "SPX": "Cairo",
    "CTA": "Catania",
    "CHQ": "Chania (Crete)",
    "RMO": "Chisinau",
    "CLJ": "Cluj-Napoca",
    "CGN": "Cologne",
    "CIY": "Comiso",
    "CND": "Constanta",
    "CPH": "Copenhagen",
    "CFU": "Corfu",
    "CRA": "Craiova",
    "DLM": "Dalaman",
    "DMM": "Dammam",
    "DEB": "Debrecen",
    "DTM": "Dortmund",
    "DXB": "Dubai",
    "DBV": "Dubrovnik",
    "EIN": "Eindhoven",
    "EBL": "Erbil",
    "FAO": "Faro",
    "HHN": "Frankfurt",
    "FDH": "Friedrichshafen",
    "FUE": "Fuerteventura",
    "FNC": "Funchal (Madeira)",
    "GDN": "Gdansk",
    "GVA": "Geneva",
    "GOA": "Genoa",
    "GRO": "Girona",
    "GLA": "Glasgow",
    "GOT": "Gothenburg",
    "LPA": "Gran Canaria",
    "GNB": "Grenoble",
    "HAM": "Hamburg",
    "HAU": "Haugesund",
    "HER": "Heraklion (Crete)",
    "HRG": "Hurghada",
    "IAS": "Iasi",
    "IBZ": "Ibiza",
    "IST": "Istanbul",
    "ADB": "Izmir",
    "JED": "Jeddah",
    "FKB": "Karlsruhe/Baden-Baden",
    "KTW": "Katowice",
    "KUN": "Kaunas",
    "EFL": "Kefalonia",
    "KGS": "Kos",
    "KSC": "Kosice",
    "KRK": "Krakow",
    "KUT": "Kutaisi",
    "LCA": "Larnaca",
    "LBA": "Leeds",
    "LEJ": "Leipzig",
    "LIS": "Lisbon",
    "LPL": "Liverpool",
    "LJU": "Ljubljana",
    "LGW": "London Gatwick",
    "LTN": "London Luton",
    "LUZ": "Lublin",
    "LYS": "Lyon",
    "MAD": "Madrid",
    "AGP": "Malaga",
    "MLE": "Male",
    "PMI": "Mallorca",
    "MMX": "Malmo",
    "MLA": "Malta",
    "RAK": "Marrakech",
    "RMF": "Marsa Alam",
    "FMM": "Memmingen",
    "MXP": "Milan Malpensa",
    "BGY": "Milan Bergamo",
    "MCT": "Muscat",
    "MED": "Medina",
    "JMK": "Mykonos",
    "NAP": "Naples",
    "NCE": "Nice",
    "INI": "Nis",
    "NUE": "Nuremberg",
    "OHD": "Ohrid",
    "OLB": "Olbia",
    "OSL": "Oslo",
    "TRF": "Oslo Sandefjord",
    "ORY": "Paris Orly",
    "BVA": "Paris Beauvais",
    "PEG": "Perugia",
    "PSR": "Pescara",
    "PSA": "Pisa",
    "PDV": "Plovdiv",
    "TGD": "Podgorica",
    "TAT": "Poprad-Tatry",
    "OPO": "Porto",
    "POZ": "Poznan",
    "PRG": "Prague",
    "PRN": "Pristina",
    "RDO": "Radom",
    "KEF": "Reykjavik",
    "RHO": "Rhodes",
    "RIX": "Riga",
    "RMI": "Rimini",
    "RUH": "Riyadh",
    "CIA": "Rome Ciampino",
    "FCO": "Rome Fiumicino",
    "RZE": "Rzeszow",
    "SLL": "Salalah",
    "QSR": "Salerno",
    "SZG": "Salzburg",
    "SKD": "Samarkand",
    "SDR": "Santander",
    "JTR": "Santorini",
    "SJJ": "Sarajevo",
    "SUJ": "Satu Mare",
    "SVQ": "Sevilla",
    "SSH": "Sharm El Sheikh",
    "SBZ": "Sibiu",
    "JSI": "Skiathos",
    "SKP": "Skopje",
    "SOF": "Sofia",
    "HMB": "Sohag",
    "SPU": "Split",
    "SVG": "Stavanger",
    "ARN": "Stockholm Arlanda",
    "NYO": "Stockholm Skavsta",
    "STR": "Stuttgart",
    "SCV": "Suceava",
    "SZZ": "Szczecin",
    "TLL": "Tallinn",
    "TAS": "Tashkent",
    "TLV": "Tel Aviv",
    "TFS": "Tenerife",
    "SKG": "Thessaloniki",
    "TSR": "Timisoara",
    "TIA": "Tirana",
    "TGM": "Tirgu-Mures",
    "TRS": "Trieste",
    "TOS": "Tromso",
    "TRD": "Trondheim",
    "TRN": "Turin",
    "HSA": "Turkistan",
    "TKU": "Turku",
    "TZL": "Tuzla",
    "VLC": "Valencia",
    "VAR": "Varna",
    "VCE": "Venice Marco Polo",
    "TSF": "Venice Treviso",
    "VRN": "Verona",
    "VIE": "Vienna",
    "VNO": "Vilnius",
    "WAW": "Warsaw",
    "WRO": "Wroclaw",
    "EVN": "Yerevan",
    "ZTH": "Zakynthos",
    "ZAZ": "Zaragoza",
}
